/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as VerifyOtpRouteImport } from './routes/verify-otp';
import { Route as TodoRouteImport } from './routes/todo';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as LoginRouteImport } from './routes/login';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as ChatRouteImport } from './routes/chat';
import { Route as R404RouteImport } from './routes/404';
import { Route as IndexRouteImport } from './routes/index';
import { Route as RoomIdRouteImport } from './routes/room.$id';
const VerifyOtpRoute = VerifyOtpRouteImport.update({
    id: '/verify-otp',
    path: '/verify-otp',
    getParentRoute: () => rootRouteImport,
});
const TodoRoute = TodoRouteImport.update({
    id: '/todo',
    path: '/todo',
    getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
});
const ChatRoute = ChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => rootRouteImport,
});
const R404Route = R404RouteImport.update({
    id: '/404',
    path: '/404',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const RoomIdRoute = RoomIdRouteImport.update({
    id: '/room/$id',
    path: '/room/$id',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    R404Route: R404Route,
    ChatRoute: ChatRoute,
    ForgotPasswordRoute: ForgotPasswordRoute,
    LoginRoute: LoginRoute,
    ProfileRoute: ProfileRoute,
    RegisterRoute: RegisterRoute,
    TodoRoute: TodoRoute,
    VerifyOtpRoute: VerifyOtpRoute,
    RoomIdRoute: RoomIdRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
