/* eslint-disable */
// This file is auto-generated by TanStack Router
// Do not edit this file manually

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'

const rootRouteWithContext = rootRoute

export const routeTree = rootRouteWithContext.addChildren([IndexRoute])
